# flowable
flowable:
  # true 会对数据库中所有表进行更新操作。如果表不存在，则自动创建(建议开发时使用)
  database-schema-update: false
  # 关闭定时任务JOB
  async-executor-activate: false
  # 禁用身份服务
  identity-lookup-enabled: false
  # 关闭事件日志
  event-logging-enabled: false
  # 关闭表单引擎
  form-engine-enabled: false